language: c

env:
- CROSS_COMPILE=$HOME/gcc-arm-none-eabi/bin/arm-none-eabi-

compiler: gcc

install: 
- ./.travis_scripts/install_toolchain.sh  

script:
- cp configs/cm0p_default_defconfig ./.config
- make ARCH=cm0p cm0p_default_defconfig

        
