language: c

env:
- ARCH=arm
- CROSS_COMPILE=$HOME/gcc-arm-none-eabi/bin/arm-none-eabi-

compiler: arm-none-eabi-gcc

install: 
- ./.travis_scripts/install_toolchain.sh  

script:
- cp configs/cm0p_default_defconfig ./.config
- make 

        
